server:
  port: 8806

spring:
  application:
    name: spring-boot-shiro
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_shiro?serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/


shiro:
  loginUrl: /user/login
  userNativeSessionManager: true
  sessionIdUrlRewritingEnabled: false