
# 应用名称
spring:
  application:
    name: email
  mail:
    host: smtp.163.com
    username: jushouqingtian@163.com
    password: RPZMCPVJPURTPMUI
    protocol: smtp
  freemarker:
    template-loader-path: classpath:/email/
    cache: false
    charset: UTF-8
server:
  port: 8805
