spring:
  application:
    name: spring-boot-orm-jpa
  #数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myapp?serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true
