server:
  port: 8080
spring:
  application:
    name: socketio
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
     # password:
ws:
  server:
    ip: 127.0.0.1
    port: 8089


